groups:
  - name: revenue
    owner:
      name: gokul
      email: gokul@gmail.com

models:
  - name: stg_orders
    group: revenue
    access: protected

  - name: stg_products
    group: revenue
    access: public

  - name: stg_customers
    group: revenue
    access: private

  - name: stg_transactions
    group: revenue
    access: public
